[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mae_model"
version = "1.0.0"
description = "MAE Model MedMNIST Predictor Package"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "torch",
    "torchvision",
    "timm"
]

[tool.setuptools.packages.find]
include = ["models*"]